### ISSUE TITLE
Fix building of ctypes on macosx

### ISSUE THREAD

**Issue by jcfr** [python-cmake-buildsystem/python-cmake-buildsystem#18]
See https://github.com/davidsansome/python-cmake-buildsystem/blob/master/cmake/extensions/CMakeLists.txt#L131-187

**Comment by pieper** [comment]
Started looking at this.  This fix is close, but a bug in mac ffi [2] means that a symbol is not defined in python 2.7.3.  The fix was added to a later python version, but that's not possible to add due to issue #41.


[1] https://github.com/pieper/python-cmake-buildsystem/commit/291e91681834dc243b57c8c163c3cbad6cfa09ab


[2] http://python.6.x6.nabble.com/issue9662-ctypes-not-building-under-OS-X-because-of-ffi-closure-free-not-being-defined-early-enough-td764678.html

**Comment by jcfr** [comment]
Hi Steve, there is a topic on my fork named ci-support-2.7.8 that should be
testedbinstead.

Thanks
Jc

**Comment by pieper** [comment]
Thanks Jc - I ran out of steam on trying to get ctypes working on mac and I'm trying a different approach to my original problem.

For the record Jc is referring to this branch:

https://github.com/jcfr/python-cmake-buildsystem/commits/ci-support-v2.7.8
